In [1]:
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [2]:
idx2name={
    
}
files=os.listdir()
pics=[]
labels=[]
Y=[]
cnt=0
for f in files:
    if f.endswith(".npy"):
        data=np.load(f)
        labels=np.ones(data.shape[0],dtype='int32')*cnt
        pics.append(data)
        idx2name[cnt]=f[:-4]
        Y.append(labels)
        cnt+=1

In [3]:
X=np.vstack(pics)
print(X.shape)


(80, 100, 100, 3)


In [4]:
Y=np.asarray(Y)
Y=Y.reshape(80,)

In [5]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
X.shape,Y.shape

((80, 100, 100, 3), (80,))

In [7]:
def dist(a,b):
    return np.sum((a-b)**2)**.5
def knn(X,Y,test_point,k=5):
    
    #1 find distance from all point
    d=[]
    m=X.shape[0]
    for i in range(m):
        curent_dis=dist(X[i],test_point)
        d.append((curent_dis,Y[i]))
    
    d.sort();
    d=np.array(d[0:k])
    d=d[ :,1]
    uniq,occ=np.unique(d,return_counts=True)
    print(uniq,occ)
    indx=np.argmax(occ)
    pred=uniq[indx]

    return idx2name[int(pred)]

In [8]:
test_point=X[45]

In [9]:
knn(X,Y,test_point)

[2.] [5]


'rk'

In [10]:
camera=cv2.VideoCapture(0)

In [11]:
facedetector=cv2.CascadeClassifier('facetmp.xml')
while True:
    b,img=camera.read()
    
    if b==False:
        continue
    #detect face
    faces=facedetector.detectMultiScale(img,1.3,5)
    #no facesc detected
    if(len(faces)==0):
        continue
    
    #draw a bounding box
    for f in faces:
    
        green=(255,0,0)
    
        x,y,w,h=faces[0]
        cv2.rectangle(img,(x,y),(x+w,y+h),green,5)
        cropped_faces=img[y:y+h,x:x+w]
        cropped_faces = cv2.resize(cropped_faces,(100,100))
        pred=knn(X,Y,cropped_faces)
        cv2.putText(img, pred, (x, y-20), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), lineType=cv2.LINE_AA) 
 
    cv2.imshow("Title",img)
    #Add some delay 1 ms between 2 frames
    key=cv2.waitKey(1)&0xFF
    if key==ord('q'):
        break
    
camera.release()
cv2.destroyAllWindows()

pics = np.array(pics)
print(pics.shape)

np.save(name+".npy",pics)
print("Images saved to disk")



[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[0. 3.] [1 4]
[0. 3.] [1 4]
[0. 3.] [1 4]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[0. 3.] [1 4]
[3.] [5]
[3.] [5]
[3.] [5]
[0. 3.] [1 4]
[0. 3.] [1 4]
[0. 3.] [1 4]
[3.] [5]
[3.] [5]
[3.] [5]
[0. 3.] [1 4]
[3.] [5]
[3.] [5]
[0. 3.] [2 3]
[0. 3.] [2 3]
[0. 3.] [2 3]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[3.] [5]
[0. 3.] [2 3]
[0. 3.] [2 3]
[0. 3.] [2 3]
[0. 3.] [2 3]
[0. 2. 3.] [3 1 1]
[0. 2. 3.] [3 1 1]
[0. 3.] [4 1]
[0. 2. 3.] [3 1 1]
[0. 2. 3

NameError: name 'name' is not defined